# ============================================
# Perfil de DESARROLLO
# ============================================

spring:
  # ============================================
  # Base de Datos - PostgreSQL local
  # ============================================
  datasource:
    url: jdbc:postgresql://localhost:5432/acainfo_dev
    username: acainfo_dev
    password: acainfo_dev
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  # ============================================
  # JPA/Hibernate - Configuración desarrollo
  # ============================================
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
    show-sql: true  # Muestra SQL en consola

  # ============================================
  # DevTools - Recarga automática
  # ============================================
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    livereload:
      enabled: true
# ============================================
# Servidor - Puerto de desarrollo
# ============================================
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always  # Stack trace completo en desarrollo
    include-exception: true

# ============================================
# JWT - Tokens de mayor duración en desarrollo
# ============================================
jwt:
  secret: dev-secret-key-only-for-development-environment-change-in-production
  access-token:
    expiration: 3600000  # 1 hora (más largo para desarrollo)
  refresh-token:
    expiration: 2592000000  # 30 días

# ============================================
# Logging - Nivel detallado
# ============================================
logging:
  level:
    root: INFO
    com.acainfo.backend: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.stat: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36}) - %msg%n"
  file:
    name: logs/acainfo-dev.log

# ============================================
# Swagger - Habilitado con todas las opciones
# ============================================
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
    filter: true
    display-request-duration: true
    display-operation-id: true
    deep-linking: true
    show-extensions: true
    show-common-extensions: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  show-actuator: true

# ============================================
# CORS - Más permisivo en desarrollo
# ============================================
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:4200
    - http://localhost:5173
    - http://127.0.0.1:3000
    - http://127.0.0.1:5173
  allowed-methods:
    - "*"
  allowed-headers:
    - "*"
  exposed-headers:
    - "*"
  allow-credentials: true
  max-age: 3600

# ============================================
# Actuator - Todos los endpoints expuestos
# ============================================
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
  httpexchanges:
    recording:
      enabled: true

# ============================================
# Configuración de desarrollo adicional
# ============================================
debug: true  # Activa el modo debug de Spring Boot
